spring.application.name=TaskFlow

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow
spring.datasource.username=lucaslima
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=3bc3af9d4aef8f6d92b8f46f11bdb64d8a5d2c6c1f8a9b4e7d6c5a4b3f2e1d
jwt.expiration=86400000